baseurl = "https://palashraghuwanshi.com/"
googleAnalytics = "G-KD0VM5DJ1B"
languageCode = "en-us"
paginate = 6
summaryLength = "10"
theme = "parsa-hugo"
title = "Peelu Blogs"
[markup.goldmark.renderer]
unsafe = true

# navigation
[[menu.main]]
name = "Home"
url = "http://palashraghuwanshi.com/"
weight = 1
hasChildren = true

[[menu.main]]
name = "Contact"
url = "contact/"
weight = 3

[[menu.main]]
name = "About"
url = "about/"
weight = 2

[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
address = "Kanhaiya Hazari Ka Bada, Vidisha (M.P), India"
author = "Peelu"
author_image = "images/banner-img.png"
bio = "I’m interested in learning new activities day by day."
contact_form_action = "#"
copyright = "Copyright &copy; 2022 a theme by [themefisher.com](https://themefisher.com)"
description = "Brain Psychology Arduino IOT"
email = "palashraghuwanshi16@gmail.com"
home = "Home"
layout = "1"
logo = "images/logo.png"
mobile = "+91 9174151700"
preloader = true
search = true
[params.cookies]
enable = true
expire_days = 2
[params.instafeed]
access_token = "IGQVJYeUk4YWNIY1h4OWZANeS1wRHZARdjJ5QmdueXN2RFR6NF9iYUtfcGp1NmpxZA3RTbnU1MXpDNVBHTzZAMOFlxcGlkVHBKdjhqSnUybERhNWdQSE5hVmtXT013MEhOQVJJRGJBRURn"
enable = true
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/headroom/headroom.js"
[[params.plugins.js]]
link = "plugins/instafeed/instafeed.min.js"
[[params.plugins.js]]
link = "plugins/masonry/masonry.js"
[[params.plugins.js]]
link = "plugins/reading-time/readingTime.min.js"
[[params.plugins.js]]
link = "plugins/smooth-scroll/smooth-scroll.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[[params.social]]
icon = "ti-facebook"
link = "https://www.facebook.com/palash.raghuwanshi.378"
[[params.social]]
icon = "ti-twitter-alt"
link = "https://twitter.com/peeludev"
[[params.social]]
icon = "ti-linkedin"
link = "https://www.linkedin.com/in/palash-raghuwanshi-520412109/"
[[params.social]]
icon = "ti-github"
link = "https://github.com/Peelu-Dev/"
[[params.social]]
icon = "ti-instafeed"
link = "https://www.instagram.com/peelu_raghuwanshi1/"
